apiVersion : apps/v1
kind: Deployment
metadata:
  name: "fabmedicalkay-e51a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "fabmedicalkay-e51a"
  template:
    metadata:
      labels:
        app: "fabmedicalkay-e51a"
    spec:
      containers:
        - name: "fabmedicalkay-e51a"
          image: "fabmedicalkay.azurecr.io/fabmedicalkay"
          ports:
          - containerPort: 80